DOMAIN = "eaton_upsc"

DEFAULT_PORT = 4679
DEFAULT_SCAN_INTERVAL = 30

PLATFORMS = ["sensor"]
DATA_COORDINATOR = "coordinator"

STATUS_ON_BATTERY = "on_battery"
STATUS_ON_UTILITY = "on_utility"
UPS_STATUS = [STATUS_ON_BATTERY, STATUS_ON_UTILITY]

